### PR TITLE
prevent hanging on Windows

### PR DESCRIPTION
**Pull request by chorny**

### CODE REVIEW

**Comment by dacav** [comment]
Hello Chorny. A bit of discussion, if you don't mind:

Fix infinite loop:
----

How is this working on Windows? By using this snippet:

    perl -MFile::Spec::Win32 -E 'say File::Spec::Win32->rootdir'

I was able to understand that `rootdir` is defined as `\`. How is the empty string being preventing the loop? Are there cases in which going one level up you get empty string?

Incorrectly resolved ambiguity
----

I don't see how explicitly specifying `$_` will change the code. I don't see the ambiguity you are trying to prevent:

- `defined` will use `$_` unless specified
- `defined` works as unary operator, which bounds with precedence over the `?:` operator.

Could you be more specific?

**Comment by chorny** [comment]
1. File::Spec::Win32->rootdir should not be used, it is just inherited from File::Spec::Unix. So I added to check that using upper directory does not change current directory.


2. 
Without this change it show a warning:
```
Warning: Use of "defined" without parentheses is ambiguous at blib/lib/PFT/Date.pm line 61.
Use of ?PATTERN? without explicit operator is deprecated at blib/lib/PFT/Date.pm line 61.
```
which shows that '?' was interpreted as regex start.
See for ex. http://www.cpantesters.org/cpan/report/25054418-002d-11e6-bbed-e5eefcd2507e

**Comment by dacav** [comment]
Merged, thank you.
It's weird I didn't get such warnings on my system, anyway o_O
Do you have some suggestions about this?

**Comment by chorny** [comment]
You use perl 5.22? Maybe it was fixed in this version. As you used feature of perl 5.22, it may be easier for you just to require perl 5.22.

**Comment by dacav** [comment]
Yes, my `perl -v` gives 5.22.

I'm not using features of 5.22 that I know. I'm using 5.16 all the way in order to get proper unicode support, and I never got warnings.

**Pull request merged**
